name: 'Delete outdated git tags'
description: 'Deletes git tags that where produced by deleted feature branches.'
author: 'Nils Diekmann'

inputs:
  token:
    description:
      'Token for authentication. if not provided, the GITHUB_TOKEN secret will
      be used.'
    default: ${{ github.token }}
    required: false

runs:
  using: node24
  main: dist/index.js
